# Generated by Django 4.0 on 2023-06-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
