# Generated by Django 4.0 on 2023-06-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_book_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
