# Generated by Django 4.0 on 2023-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='transaction_image',
            field=models.ImageField(default='default_image.jpg', upload_to='transaction_images/'),
        ),
    ]
